name: Windows - Manual Build
on:
  push:
    branches:
    - main
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
    - closed
    branches:
    - main
jobs:
  build-windows-latest:
    runs-on: windows-latest
    steps:
    - name: Check out
      uses: actions/checkout@v3
    - name: Configure Git
      run: >-
        git config user.name "GitHub Action"

        git config user.email "action@github.com"
    - name: Extract Version
      id: extract_version
      run: >

        # Running on Windows 

        apt-get update
        apt-get install -y libxml2-utils
        bash -c version_number=$(xmllint --xpath \"string(//Version)\" GithubActionExpressionTesting/GithubActionExpressionTesting.csproj)

        echo "$version_number"
        echo "version_number<<EOF" >> $GITHUB_OUTPUT 
        echo "$version_number" >> $GITHUB_OUTPUT 
        echo "EOF" >> $GITHUB_OUTPUT 
      shell: bash
    - name: Display Version
      run: 'echo "Version number: ${{ steps.extract_version.outputs.version_number }}"'
    - name: Extract Package Release Notes
      id: extract_package_release_notes
      run: >
        # Running on Windows 

        apt-get update
        apt-get install -y libxml2-utils
        bash -c package_release_notes=$(xmllint --xpath \"string(//PackageReleaseNotes)\" GithubActionExpressionTesting/GithubActionExpressionTesting.csproj)

        echo "$package_release_notes"
        echo "package_release_notes<<EOF" >> $GITHUB_OUTPUT 
        echo "$package_release_notes" >> $GITHUB_OUTPUT 
        echo "EOF" >> $GITHUB_OUTPUT 
      shell: bash
    - name: Display Package Release Notes
      run: 'echo "Package Release Notes: ${{ steps.extract_package_release_notes.outputs.package_release_notes }}"'
